version: '3.8'

services:
  frontend:
    build: .
    container_name: goldenia-wallet-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
